server:
  port: 8080
spring:
  application:
    name: info-publishing
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 5Mb
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/krstar/infopublishing/**/**.xml
  type-aliases-package: classpath:com.krstar.infopublishing.**.entity

##log
#logging:
#  config: classpath:logback.xml

#swagger
swagger:
  title: 江科大信息发布平台接口文档
  contact:
    name: CasualJi
    url: https://www.krstar.com
  base-package: com.krstar.infopublishing
  base-path: /**
  version: 1.0.RELEASE
  description: 江科大信息发布平台接口文档
  exclude-path: /error, /ops/**